Ext.define('Afisha.view.Viewport',{
    extend:'Ext.Container',
    xtype:'aviewport',
    config:{
        items:[{
            xtype:'categories'
        }],
        fullscreen:true,
        layout:'card'
    }
});